### ISSUE TITLE
backslash in side brackets of format string causes an issue.

### ISSUE THREAD

**Issue by JervenBolleman** [Kurrawong/sparql#3]
On line [237 of serializer.py](https://github.com/Kurrawong/sparql/blob/main/sparql/serializer.py#L237) there is a blackslash inside the `{}` which is a problem on my python3.11.6 as shipped with Ubuntu 23.10.

```
Traceback (most recent call last):
  File "/home/jbollema/git/sparql-examples/formatQuery.py", line 2, in <module>
    from sparql.parser import sparql_parser
  File "/home/jbollema/git/sparql-examples/venv/lib/python3.11/site-packages/sparql/__init__.py", line 5, in <module>
    from sparql.serializer import SparqlSerializer
  File "/home/jbollema/git/sparql-examples/venv/lib/python3.11/site-packages/sparql/serializer.py", line 237
    self._result += f"\n{'\t' * self._indent}}}"
                                             ^
```

**Comment by edmondchuc** [comment]
Hi @JervenBolleman, thanks for your issue.

Do you mind providing an example query containing a backslash that is causing the issue?

I tried with the following query and it worked fine for me. It contains a backslash inside the curly braces of the `QuadsNotTriples` production.

```sparql
WITH <g>
INSERT {
    GRAPH <g> {
        <s> <p> "f\" .
    }
}
WHERE {}
```

The output is not perfect with the indentations, but I get without any errors:

```sparql
WITH <g> INSERT {
GRAPH <g> {
		<s> <p> "f\" . 
	}
}WHERE {

}
```

**Comment by edmondchuc** [comment]
Hi @JervenBolleman, I just tested and it looks like there's an issue in Python 3.11. Using this package on Python 3.12 works fine.

We don't have any immediate plans to allow for support with 3.11. If you can pinpoint what the exact issue is, we'll be happy to fix it.

**Comment by JervenBolleman** [comment]
Hi @edmondchuc the logic in [line 237 of serializer.py](https://github.com/Kurrawong/sparql/blob/main/sparql/serializer.py#L237)

```python
elif child.value == "}":
     self._result += f"\n{'\t' * self._indent}}}"
```
should maybe be something like
```python
elif child.value == "}":
     tabs= '\t' * self._indent
     self._result += "\n"
     self._result += tabs
```
